import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import './globals.css'
import { Footer } from '@/components/footer'
import { SessionProvider } from "next-auth/react"

export const metadata: Metadata = {
  title: 'SPdf',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          {children}
          <Footer />
          <Toaster richColors position='top-right' />
        </SessionProvider>
      </body>
    </html>
  )
}
