import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/footer";



export const metadata: Metadata = {
  title: "SPdf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={``}>
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
