import type { Metadata } from 'next'
import { Toaster } from 'sonner'
import './globals.css'
import { Footer } from '@/components/footer'
import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'SPdf',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={``}>
      <body>
        {children}
        <Footer />
        <Toaster richColors position='top-right' />
      </body>
    </html>
  )
}
